# Configuration
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsdoc/recommended
  - plugin:mocha/recommended
env:
  browser: true
  node: true
  mocha: true
  es6: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - import
  - jsdoc
  - mocha
settings:
  react:
    version: detect

# Rules
rules:
  
  # Active rules
  import/order:
    - warn
    - 
      groups:
        - external
        - builtin
        - internal
        - sibling
      pathGroups:
        - pattern: "@reducers/**"
          group: external
          position: after
          
        - pattern: "@components/**"
          group: internal
          position: after
        - pattern: "@constants/**"
          group: internal
          position: after
        - pattern: "@pages/**"
          group: internal
          position: after
        - pattern: "@styles/**"
          group: internal
          position: after
      pathGroupsExcludedImportTypes:
        - internal
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  import/no-unresolved:
    - error
    - ignore:
      - "^@"
  jsdoc/newline-after-description:
    - warn
    - never
  jsdoc/require-jsdoc:
    - warn
    - require:
        FunctionDeclaration: false
  jsdoc/require-param:
    - warn
    - enableFixer: false
  no-multiple-empty-lines:
    - warn
    - max: 1
  no-unused-vars: warn
  no-console:
    - warn
    - allow:
      - warn
      - error
      - info
  semi:
    - error
    - always
  spaced-comment:
    - warn
    - always
    - exceptions:
      - '*'

  # Overridden and disabled rules
  mocha/handle-done-callback: off
  no-case-declarations: off
  no-useless-escape: off
  react/prop-types: off
  react/display-name: off
  quotes: off
